### ISSUE TITLE
Repo is not working

### ISSUE THREAD

**Issue by jar361** [samsung-cnct/chart-curator#11]
Error: Looks like "https://quay.io/samsung_cnct/chart-curator" is not a valid chart repository or cannot be reached: Failed to fetch https://quay.io/samsung_cnct/chart-curator/index.yaml : 404 Not Found

Are you interested in moving this to https://github.com/kubernetes/charts?

**Comment by leahnp** [comment]
Hey @jar361 we are in the middle of a charts overhaul, this chart has moved to: https://quay.io/repository/samsung_cnct/curator-container sorry about that inconvenience, I will update the documentation.

We would consider moving this chart upstream - has there been a community interest in an official curator chart?

**Comment by leahnp** [comment]
Hey @jar361 we are in the middle of a charts overhaul, this chart has moved to: https://quay.io/application/samsung_cnct/curator sorry about that inconvenience.

We would consider moving this chart upstream - has there been a community interest in an official curator chart?

**Comment by jar361** [comment]
Yes.  We currently are getting a lot of interest in ELK stack in kubernetes-charts.  I am willing to help push this upstream.

**Comment by rendhalver** [comment]
We are still seeing a problem adding this repo:
$ helm repo add curator https://quay.io/application/samsung_cnct/curator
Error: Looks like "https://quay.io/application/samsung_cnct/curator" is not a valid chart repository or cannot be reached: error converting YAML to JSON: yaml: line 51: mapping values are not allowed in this context

**Comment by DStorck** [comment]
have you tried running `helm registry install quay.io/samsung_cnct/curator`? it shouldn't be installed with `helm repo add` as far as i know

**Comment by rendhalver** [comment]
When I run helm dep up it says I need to add the repo that way.
There is no registry sub command in recent helm installs.

**Comment by DStorck** [comment]
To install curator on a running cluster, you should just have to run this one command: ```helm registry install quay.io/samsung_cnct/curator```  We are hosting this on quay's app registry, so you need to install the [registry plugin](https://github.com/app-registry/appr-helm-plugin/blob/master/README.md#install-the-helm-registry-plugin) to be able to use this.

**Comment by rendhalver** [comment]
If we try and use this repo for the elastic-stack PR mentioned about it will very likely fail in to build in k8s-charts CI.
How do you feel about moving this into the official kubernetes/charts repo?
We can help you get that setup.

**Comment by DStorck** [comment]
Yes I would be interested in doing this, what are the logistics?

**Comment by rendhalver** [comment]
Short version:
- read the technical requirements https://github.com/kubernetes/charts/blob/master/CONTRIBUTING.md#technical-requirements
- sign the CNCF agreement: https://github.com/kubernetes/community/blob/master/CLA.md
- fork the repo and add a PR: https://github.com/kubernetes/charts

Long version: https://github.com/kubernetes/charts/blob/master/CONTRIBUTING.md

If you get stuck John and I can help.
There is also the #charts channel in the official k8s slack which is good for asking questions.

**Comment by rendhalver** [comment]
The main issue is getting that change to the requirements file to work with the CI in the official k8s charts repo.

**Comment by DStorck** [comment]
where is the CI for the official k8s repo?

**Comment by rendhalver** [comment]
They use Circle-CI for some basic testing and an internal Jenkins setup for full testing.
The setup is in the repo.

**Comment by DStorck** [comment]
closing - error has been taken care of, there is now an [upstream curator](https://github.com/kubernetes/charts/tree/master/incubator/elasticsearch-curator) in kubernetes charts
