### ISSUE TITLE
Tests for curator

### ISSUE THREAD

**Issue by guineveresaenger** [samsung-cnct/chart-curator#6]
Add tests for curator. 

There will be research on how to test elasticsearch curator. 
[Curator Reference](https://www.elastic.co/guide/en/elasticsearch/client/curator/5.2/index.html)
[Curator github](https://github.com/elastic/curator)

**Comment by coffeepac** [comment]
should include:
- helm testing (linting)
- sanity check by way of installing this chart into a fresh namespace on an existing cluster

**Comment by coffeepac** [comment]
waiting for conversion to GITLAB CI

**Comment by mikeln** [comment]
superceeded by switch back to jenkins
