### ISSUE TITLE
port curator chart to gitlab

### ISSUE THREAD

**Issue by DStorck** [samsung-cnct/chart-curator#8]
- [x]  Follow [instructions](https://github.com/samsung-cnct/solas/blob/master/docs/gitlab.md) to create  and edit`build/.gitlab-ci.yaml` from [template](https://github.com/samsung-cnct/solas-chart/blob/master/.gitlab-ci.yml)
- [x] also create `build/build.sh` and `build/test.sh` according to instructions
- [x] create secret variable in gitlab
- [x] add pipeline status badge to README
- [x] Remove the `Jenkinsfile` in the current repo.
- [x] When PR has merged, make sure that new image is being created on quay. Afterwards,  please head back to the [umbrella ticket](https://github.com/samsung-cnct/issues/issues/89) and check off the `chart-curator`

**Comment by DStorck** [comment]
test to check migration of charts

**Comment by DStorck** [comment]
work is done here: https://github.com/samsung-cnct/chart-curator/pull/9

**Comment by DStorck** [comment]
app is building successfully on quay and pipeline is building correctly

**Comment by leahnp** [comment]
LGTM
